### ISSUE TITLE
Feature: User can stream using RTMP/OBS  to their channel

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/final-project#1]
## ⚙️ Feature
User can stream using a third party software called open broadcaster software, or OBS
for short. 
## 📐 Functionality
The user will go to their channel dashboard and copy paste a stream key into their rtmp client.
The user can then start streaming, and their stream will be visible to anyone on the web.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Stream View](https://user-images.githubusercontent.com/16251746/132059439-78b47078-495d-4d32-9301-e2999f72b127.png)
![User Dashboard](https://user-images.githubusercontent.com/16251746/132059442-42e02540-2225-4b77-8115-f21b051ec5c0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create installer shell script for NGINX that compiles NGINX with an RTMP module.
- [x] Compile NGINX into the project media folder and create a runner in package.json
- [x] Listen for on_done and on_publish requests from NGINX on localhost in NGINX config files
- [x] Capture the post requests using express

### ☁️ Server
- [x] set NGINX conf on_publish to localhost:3000/streams/on_publish
- [x] set NGINX conf on_done to localhost:3000/stream/on_done
- [x] add the routes as post requests to express
- [x] Make sure only localhost can access this route.
- [x] Update the table liveUsers to reflect the information given by NGINX
- [x] Host the generated .mpd manifest files and associated video chunks using express static
### ⚡ Client
- [x] Create a component using ShakaPlayer to view DASH stream
- [x] Hash routing between channels

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
