### ISSUE TITLE
Feature: User can chat aside the stream

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/final-project#2]
## ⚙️ Feature
User can chat aside the stream in real time.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to chat on anyone's stream.

## 🖼️ Wireframes

![Stream View](https://user-images.githubusercontent.com/16251746/132060979-a26ea787-e257-49c3-be58-340039733d50.png)
![Mobile Stream View](https://user-images.githubusercontent.com/16251746/132060997-46c48969-3e9c-4f62-9fd7-a0446b295cba.png)

## ✅ Task List
message
```
{
    content: 'My message',
    userId: 1,
    userName: 'kamaii',
    channelId: 2,
    createdAt: Date.now()
}
```

- [x] Setup socket.io to relay chat messages (JSON objects)
- [x] Create a react component that acts a a front end for the socket.io API on the client side

### ☁️ Socket.IO

- [x] Setup socket.io using http to listen on the same port as express
- [x] Listen for chat messages from the client using socket.io
- [x] listen for login events and login users using JWTs
- [x] Set the userId property of the socket to the token userId
- [x] Listen for join events and subscribe sockets to a room when requested
- [x] Set the channelId property of the socket object to the room if it exists
- [x] Listen for message events and emit messages to the room a socket is in
- [x] Log the message in postgres with timestamps
- [x] Log messages to postgress with timestamps
- [x] Give message history to a socket for a room when requested using the API
- [x] Relay messages to other sockets in the same room (userId)  when a user messages using io.emit.to()

### ☁️ Express
- [x] Create a route to receive the last 100 messages of a channel on /api/channel/messages

### ⚡ Client

- [x] Create a Chat component that renders if the hash route is equal to #channel aside the stream
- [x] If the component did mount, setup socket io to listen for message events from that channel by:
    - [x] Emiting a join event with the channelId of the channelId search param
    - [x] Sending a fetch request to /api/channel/:channelId/messages to retrieve message history
    - [x] on fetch complete, set the messages property of the state to the returned array
- [x] In the render method, map through the messages in state and render them.

- [x] Make sure the page looks good on mobile and desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
