### ISSUE TITLE
Feature: User can upload user avatar

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/final-project#37]
## ⚙️ Feature
User can upload an avatar for their account.
## 📐 Functionality
User will click on the user dashboard, and click a button that opens an upload dialogue

## ✅ Task List

- [x] Research multer

- [x] Install and import multer
- [x] Create a route for posting profile pictures that uses auth middleware
- [ ] Convert the file to a png?
- [ ] Write the file to /public/avatar/${userId}.png

### ⚡ Client

- [ ] Update dashboard to open an upload file dialogue
- [ ] Send a post requestr to /api/avatar

### 🧑‍⚕️ Clean Up
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
