### ISSUE TITLE
Feature: User can upload and  manage emotes.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can upload emotes to their channel using the channel dashboard.

## 📐 Functionality

The user uploads an emote with a name and it will show up in their channel emotes.

## 🖼️ Wireframes

![User Dashboard (1)](https://user-images.githubusercontent.com/16251746/132068383-6486017c-7139-49dd-b2a1-7833eaa52594.png)
![User dashboard mobile](https://user-images.githubusercontent.com/16251746/132068544-f21d086d-8bc3-41bb-8b40-49b2c882359e.png)

## ✅ Task List

- [ ] Create a new component that contains a file upload button a text input and a label,
- [ ] Create a new component that displays emotes
- [ ] Add a button to the emote that deletes the emote
- [ ] When the user clicks the upload button, create a request to /api/emotes/uid/upload
- [ ] When  the user click the delete button, create a  delete request to /api/emotes/uid/emoteid/

- [ ] On the server, handle the routes and query postgress

### ☁️ Server
- [ ] Update `server/index.js` to handle the route /api/emotes/uid/upload
- [ ] Update to handle /api/emotes/uid/upload

### ⚡ Client

- [ ] Create a component to  display emotes
- [ ] Create a component to display emote manager in channel dashboard

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
