### ISSUE TITLE
Feature: Move RTMP server to another repository.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/final-project#41]
## ✅ Task 

- [ ] Create a repo for kamaiitv-rtmp
- [ ] Remove RTMP dependency from any files in the project
- [ ] Add the columnds string url, int serverId to the streams table
- [ ] Create a rtmp table with columns serial serverId, inet ip, string url, int load
- [ ] Add the route /api/streams/:channelId which returns the absolute URL of the channels stream by joining the server table
- [ ] See kamaiitv-rtmp repo for rtmp backend tasks
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
